### ISSUE TITLE
Setting a hostname causes an incorrect command to be generated

### ISSUE THREAD

**Issue by jonleighton** [threatstack/threatstack-chef#2]
When setting a hostname, [this line](https://github.com/threatstack/threatstack-chef/blob/master/recipes/default.rb#L32) will cause the command to get generated without a space between the hostname and the `--ruleset` option:

```
cloudsight setup --deploy-key=123 --hostname=somename--ruleset=...
```

**Comment by petecheslock** [comment]
Hey @jonleighton thanks for reporting.  Got the fix https://github.com/threatstack/threatstack-chef/commit/e5e15d7cff640fe2a3ca465ec795e2c62a1aa33b and will get this merged and shipped out shortly to the supermarket.

**Comment by jonleighton** [comment]
Thanks
