### ISSUE TITLE
execute wget resource is not idempotent

### ISSUE THREAD

**Issue by petecheslock** [threatstack/threatstack-chef#21]
@tmclaugh fyi - this code https://github.com/threatstack/threatstack-chef/blob/master/recipes/rhel.rb#L19-L22 won't be idempotent and will fire the resource each chef run.  can you test to see if the remote_file resource will work on the affected versions of rhel and centos?  https://docs.chef.io/resource_remote_file.html

You can use the `checksum` resource property to ensure the file is not downloaded if it already exists.  

```
checksum
Ruby Type: String

Optional, see use_conditional_get. The SHA-256 checksum of the file. Use to prevent a file from being re-downloaded. When the local file matches the checksum, the chef-client does not download it.
```

**Comment by tmclaugh** [comment]
resource was idempotent but still moved to remote_resource for correctness.

**Comment by tmclaugh** [comment]
I commited a change last week for this
