### ISSUE TITLE
Allow using run_state for setting the deploy_key instead of node attributes

### ISSUE THREAD

**Issue by ColmHally** [threatstack/threatstack-chef#38]
Hi, we've just started using Threatstack and it's going great. I just have one nitpick with this cookbook:

Currently, to specify the deploy key, you need to set it as a node attribute or read it from an encrypted databag. If you're not using encrypted databags, then this `deploy_key` value ends up in clear-text in your chef server and is accessible to all other nodes/users managed by that server.

Personally, I would prefer not to have this value stored in the node attributes on the chef server nor would I like to use encrypted data bags; we're using Chef Vault right now. I'm not sure what your plans are for Chef Vault integration, but a far more flexible solution - akin to your attribute setting - would be to obtain the `deploy_key` from a `run_state` variable if it exists. For example:

```
node.run_state['threatstack']['deploy_key'] = 'ts_deploy_key'
```

Because `run_state` is discarded at the end of the `chef-client` run, this change would prevent the value from being stored in the node attributes on the chef server.

We're users of the `chef-datadog` cookbook as well and they do something similar using a library: https://github.com/DataDog/chef-datadog/blob/master/libraries/recipe_helpers.rb

Is this something you might consider adding?

**Comment by tmclaugh** [comment]
I would totally consider adding this.  I'm just a little bit slower with Chef than I am compared to Puppet and Ansible, and I have no chef Vault setup here to test with currently.  I'll add this to my queue but can't guarantee an ETA right now.

**Comment by ColmHally** [comment]
Ok, great. I just want to clarify that I'm not requesting full Chef Vault integration here, just a method of providing the deploy key such that it doesn't leak outside the server being provisioned. That's what using the `run_state` would enable. https://docs.chef.io/recipes.html#node-run-state

A developer could use any secure secret distribution method they wished (Chef Vault, encrypted data bags, Hashicorp Vault, etc.) and this cookbook wouldn't care as it would be taking the deploy key as an input from the `run_state` or node's `normal` attributes.

I'd be happy to contribute a PR next week if that helps?

**Comment by tmclaugh** [comment]
That would be awesome!  It'll help me to better learn too.  Are you on the HangOps slack?  If not, we also have a customer slack I can send you an invite to.  That would let us talk in realtime.

**Comment by patcable** [comment]
Hi @ColmHally -- I dont anticipate having a ton of time to change this to not using EDBs. That said, I agree with the idea of moving the deploy key into the `run_state`. I'll take a look at this in the next week and see if I cant get something together.

**Comment by patcable** [comment]
@ColmHally Hey, circling back to this. I'm adding some code into `default.rb` to read from run_state. Just to make sure if I'm getting this right: something else (chef-vault?) would set the attribute in run_state before this cookbook is run?

**Comment by ColmHally** [comment]
Yes, exactly, A parent cookbook would set the run_state value. Coming back
to the datadog example, we use a base cookbook to read its api secret from
a chef vault and set it in the run_state for the datadog cookbook to
consume.

**Comment by patcable** [comment]
OK, this should be merged in and in version 1.7.3 of the cookbook. Let me know if it works for you!

**Comment by ColmHally** [comment]
Hey @patcable, the code in your PR looks good. I'm going to test it out today.

I think you should add this new capability to your README by the way. It's currently missing.

**Comment by petecheslock** [comment]
Added to README.md in https://github.com/threatstack/threatstack-chef/pull/44/commits/f49e01b3dbc66e36b4f44c8f86cad15392684696
