### ISSUE TITLE
run_state for deploy key

### ISSUE THREAD

**Issue by pmacdougall** [threatstack/threatstack-chef#46]
The run_state option for the API key appears to be somewhat non-standard.

AFAIK, run_state in Chef is a "true" Hash, not a Mash which is what attributes are.  Ideally you'd only have one key string for the `node.run_state['threatstack']['deploy_key']`.

To get this to pass my ChefSpec tests I had to first create a hash for `run_state['threatstack']`:
```
node.run_state['threatstack'] = {}
node.run_state['threatstack']['deploy_key'] = SOME_SECRET_VALUE
```

Not sure what the best solution going forward would be, but the README could be updated for the current implementation.  I think migrating to a single key would be more ideal but would be a breaking change for current users.

**Comment by petecheslock** [comment]
Yup - you are right - I think we should probably set it to something like `node.run_state['threatstack_deploy_key']`  Lemme do some testing, and then i'll have to update the docs/readme and bump a major release to inform users of the change

**Comment by darwin67** [comment]
it's almost been 2 years. any update on this?

**Comment by patcable** [comment]
Hey @darwin67 we actually did add this in - though bad on me for not closing the issue. The instructions on how to use it are in the readme under the [usage section](https://github.com/threatstack/threatstack-chef/blob/master/README.md#usage). Let me know if that doesn't work...

**Comment by darwin67** [comment]
Hi @patcable , the instructions in the README is the problem this issue is addressing.

I've also just tried setting
```
node.run_state['threatstack_deploy_key'] = "<deploy key>"
```
in my recipe and the wrapper cookbook failed so I doubt this issue is actually resolved.

**Comment by patcable** [comment]
Hey, sorry about that - I misread this issue as the original request for the `run_state` variable. (#38)

Did you try the suggestion that was posted in the original post? I can forward this to some folks and see if we could get the full thing changed, though we're a bit weary of introducing breaking changes into this cookbook too.

**Comment by darwin67** [comment]
Yes, I did try the suggestion in the original post and that is working.

It doesn't need to be breaking changes but adding the option to have `node.run_state['threatstack_deploy_key']` would be awesome though.

Considering the low frequency this cookbook is getting updated, doesn't seem like having 2 options for setting the deploy_key in `run_state` could cause issues in the near future.
