### ISSUE TITLE
Agent Upgrades

### ISSUE THREAD

**Issue by anfleene** [threatstack/threatstack-chef#5]
Hi! Thanks for this cookbook it's super easy to use. 

One minor issue we've run into is with upgrading the agent. We lock the agent version with a wrapper cookbook but in order to get the new agent configured it appears you have to run `cloudsight setup` again but the .audit file persists between versions. So to do the upgrade we need to delete the .audit file before running the default recipe.

 Could the setup command run via a notification from the package resource? My understanding is that `cloudsight setup` needs to run every time the package resource runs so a notification seems like a good approach.

Thanks,
Andy

**Comment by petecheslock** [comment]
You know that is a good point - and something we probably should do.  In the past we had cloudsight setup run as a notification from the package resource, but watched almost a "catch all" if for whatever reason it failed, it could pick up on the next chef run.  

In the past there were reasons why `cloudsight setup` had to run post install, mainly a dynamic portion of the configuration file that was adjusted based on the resources of the instances (memory, cpu, etc), That is going to shortly be split out so it's more flexible.  

Are you seeing a situation where you have to run the `cloudsight setup` post upgrade?  I'm pretty sure if the package upgrades it should upgrade and restart the service.  We can do some testing to confirm that.  

Let me know.  Alternatively we could subscribe the command resource to the package resouce, but I'd have to test to see what happens with that `not_if` there

**Comment by anfleene** [comment]
>Are you seeing a situation where you have to run the cloudsight setup post upgrade? I'm pretty sure if the package upgrades it should upgrade and restart the service. We can do some testing to confirm that.

Yeah, it installs the new version but we have to run setup to get the agent to start reporting again. It stops the old agent but it doesn't start up the new one. I tried manually starting it up to see if that was all it needed but it didn't start reporting again until I did a setup. 

We run the agent on Amazon Linux fwiw. I'm also just adjusting the version and leaving the package resource action set to install not sure if that matters or not.

**Comment by petecheslock** [comment]
@anfleene hmm - that might be a bug with the package and Amazon linux - got our engineers taking a look at that right now.  FWIW we haven't see that with the Ubuntu version of the package, at least the normal operation should be to upgrade and start the agent after the fact.

**Comment by anfleene** [comment]
Great, Thanks!

**Comment by petecheslock** [comment]
Hey @anfleene just wanted to let you know we've done some testing and confirmed this is actually a bug in the agent init scripts that happen on upgrade.  We have a fix we are testing now and should be making this available in the next agent release.  I'll leave this open until then and will let you know which version has the fix.

Thanks!

**Comment by anfleene** [comment]
Awesome! Thanks @petecheslock!

**Comment by petecheslock** [comment]
Hey sorry just closing the loop here - this was fixed in the latest release of the agent we shipped in November.  If you are seeing this issue still with the latest release let me know and we'll revisit.

Thanks!
