### ISSUE TITLE
Unable to build for AMIs - configure_agent removed

### ISSUE THREAD

**Issue by joshbranham** [threatstack/threatstack-chef#56]
As part of https://github.com/threatstack/threatstack-chef/pull/54 the `default['threatstack']['configure_agent']` attribute was removed from this cookbook. We rely on this heavily to bake AMIs with the agent, then just activate them via Chef post boot in an environment. Can anyone provide what the best method is to keep this functionality? I see the attribute `default['threatstack']['agent_config_args']` but I don't see any option there to disable the agent activation via that array. 

Thanks in advance!

**Comment by benpatterson** [comment]
Hi @joshbranham  thanks for posting this and calling out this use case. 

You are right; the script as-is won't support your use-case. Basically if you look at the current version of `default.rb`, the difference between the AMI build and the Image deployment would be on [this line](https://github.com/threatstack/threatstack-chef/blob/902c6a334f85666874ccfcdf51e86b4462ecb883/recipes/default.rb#L53). Anything before that line would need to be executed when building the AMI, and anything after that line would be executed when you deploy the AMI into a running instance.

I'll work on fixing up the script this week to address this bug (likely with a similar true/false attribute). In the meantime, hopefully acknowledgement & an answer on how it should work is helpful for you until then.

**Comment by joshbranham** [comment]
Thank you @benpatterson I will work around it for now, but just wanted to see if that was intentional and if anyone else felt it was a good thing to have. If you want I can submit a PR with the changes?

**Comment by benpatterson** [comment]
Hi @joshbranham 

Indeed, it's a good thing to have, and no, it was not intentional. 

A PR is appreciated, but I'll put in a cycle on this, and hope to get something out in the next day or two. I'll ping you for review, though, if you're up for that.

**Comment by joshbranham** [comment]
Closing as PR was merged, thanks @benpatterson
