### ISSUE TITLE
Process Supervision / Service Recipe

### ISSUE THREAD

**Issue by anfleene** [threatstack/threatstack-chef#6]
Hi!

We've been digging into this cookbook a bit more and we're wondering if there's a process supervisor built into the TS agent. If not, would adding one to this cookbook be too opinionated? I'd be willing to contribute support for runit.

Thanks!
Andy

**Comment by petecheslock** [comment]
Hey @anfleene Sorry our notifications for opened PR's was broken for some reason and I missed this.  The threatstack agent actually has a built in process supervisor currently, so as long as the init process is started, any issues to the subprocesses will internally trigger them to restart and stay running.

Thanks,
