### ISSUE TITLE
Logic for enabling container checking is wrong

### ISSUE THREAD

**Issue by r4v5** [threatstack/threatstack-chef#64]
> `node['threatstack']['enable_containers']` - Set this to true in order to enable container observation. Note: container capability must already be installed and running.

This isn't the case; as written, it's enabled if node['threatstack']['enable_containers'] is set to _any non-nil value_, including `false`:
https://github.com/threatstack/threatstack-chef/blob/41381cd3202514518691763b1295a2ff7de5fc19/recipes/agent_setup.rb#L80

That line was probably intended to be `if node['threatstack']['enable_containers']`, which would match the documentation.

**Comment by benpatterson** [comment]
Thank you for pointing this out, @r4v5 

I have put in a PR to fix it.
