### ISSUE TITLE
Changing the ruleset attribute doesn't update the ruleset for the node

### ISSUE THREAD

**Issue by anfleene** [threatstack/threatstack-chef#7]
This hasn't been a huge issue but we setup some new instances and provisioned them into the wrong ruleset. The only way we could figure out to update it was to completely remove the package and reinstall the agent. Does the TS agent have an update command that we could use to update the ruleset/other configurations like deploy key that could be used in this cookbook. 

I realize these issues kind of blur the lines between actual support and the chef cookbook so feel free to send me to submit a support ticket if need be.

Thanks,
Andy

**Comment by petecheslock** [comment]
Right now we don't have an option at the agent level to change the ruleset the group is in.  Its an idea we've discussed before, but partly as we wouldn't want an attacker to have the abillity to change or omit the ruleset and bypass monitoring.  The way you've found to remove/install the agent is the cleanest way to do that, also you could remove the `/opt/threatstack/cloudsight/config/.audit` and `/opt/threatstack/cloudsight/config/.secret` files on disk and then re-register the agent to change the ruleset its in.  Shoot us over a support ticket if there is some different functionality you'd be interested in and we can add it as a feature request.
